import pandas as pd


#Step 00: Loading data

# INFO
"""
Abstract: This data consists of sample of Auslan (Australian Sign Language) signs. Examples of 95 signs were collected from five signers with a total of 6650 sign samples.


Data Set Characteristics:  

Multivariate, Time-Series

Number of Instances:

6650

Area:

N/A

Attribute Characteristics:

Categorical, Real

Number of Attributes:

15

Date Donated

1999-04-20

Associated Tasks:

Classification

Missing Values?

N/A

Number of Web Hits:

124867


Source:

Original Owner and Donor:

Mohammed Waleed Kadous
School of Computer Science of Engineering
University of New South Wales
Sydney NSW 2052 Australia
waleed '@' cse.unsw.edu.au


Data Set Information:

The source of the data is the raw measurements from a Nintendo PowerGlove. It was interfaced through a PowerGlove Serial Interface to a Silicon Graphics 4D/35G workstation.

This glove definitely falls into the category of "cheap and nasty". Position information is calculated on the basis of ultrasound emissions from emitters the glove to a 3-microphone "L-Bar" that sits atop a monitor. There are two emitters on the glove; and three receivers. This allows the calculation of 4 pieces of information: x (left/right), y (up/down), z (backward/forward), and roll (is the palm pointing up or down?). x, y and z are measured with 8 bit accuracy. "x, y, z" should not be taken to be the normal 3-dimensional orthogonal basis. In particular, 1 unit in the z direction is not of similar distance to 1 unit in the x or y directions. These x, y, z positions are relative to a calibration point which is when the palm is resting on the seated signer's thigh. Roll is 4 bits.

The data is susceptible to occasional "spikes" caused by random ultrasound noise. Median filters have been found to be beneficial in solving this problem.

Finger bend is generated by conductive bend sensors on the first four fingers. Values vary between 0 (straight) and 3 (fully bent). Accuracy is 2 bits. The gloves automatically apply a hysteresis filter on these bend sensors. At best, these measurements should be treated sceptically.

See past usage for a more detailed discussion on the data collection methodology.

The data was collected from five signers:

Signer -- Description -- Sessions -- Total samples/sign

Adam -- Sign linguist - PhD completed in area. -- 2 -- 8
Andrew -- Natural signer - signing since youth -- 3 -- 8
John -- Professional Auslan interpreter -- 5 -- 18
Stephen -- Professional Auslan interpreter -- 4 -- 16
Waleed -- The researcher. Novice signer -- 4 -- 20

Each session was taken at a different time, after a break, etc.

The "adam" dataset were sampled in a fixed order -- this means that they are subject to fatigue effects, etc. All other datasets were sampled in random order. The "waleed" and "stephen" datasets contain signs that begin with "cal-". These were considered as a means of calibration, but didn't work out too well.

The data presented is the raw data with no filtering.

Occasional dropouts in x, y, z values. These can be easily fixed using a median filter.

Average number of frames per instance is 51, but varies from 30 to 102.

The data is in a comma separated file containing all of the attributes mentioned above. Each sign sample is stored in a single file. The directory hierarchy is as follows:
-Each signer is in a separate directory.
-Each session from signer is in a subdirectory. Each session is denoted by a number.
-Each sample is in a file named by the sample appended with the number of the sample of that sign.

The filenames indicate the class.


Attribute Information:

x:
- Continuous.
- Description: x position between -1 and 1. Units are *approximately* metres.
y:
- Continuous.
- Description: y position between -1 and 1. Units are approximately metres.
z:
- Continuous.
- Description: z position between -1 and 1. Units are not metres.
This space should not really be treated as linear, although it is safe to
treat it as monotonically increasing.
roll:
- Continuous.
- Description: roll with 0 meaning "palm down", rotating clcokwise through to a maximum of 1 (not included), which is also "palm down".
pitch:
- Has a value of -1, indicating that it is not available for this data.
Should be ignored.
yaw:
- Has a value of -1, indicating that it is not available for this data.
Should be ignored.
thumb:
- Continuous.
- Description: Thumb bend. has a value of 0 (straight) to 1 (fully bent).
fore:
- Continuous.
- Description: Forefinger bend. has a value of 0 (straight) to 1 (fully bent).
index:
- Continuous.
- Description: Index finger bend. has a value of 0 (straight) to 1 (fully bent).
ring:
- Continuous.
- Description: Ring finger bend. has a value of 0 (straight) to 1 (fully bent).
little:
- In this case, it is a copy of ring bend. Should be ignored.
keycode:
- Indicates which key was pressed on the glove. Should be ignored.
gs1:
- glove state 1 Should be ignored.
gs2:
- glove state 2 should be ignored.
Receiver values:
- Determines if all receivers received values from all transmitters. A value of 0x3F indicates all receivers received information from all transmitters. Other values indicate this is not the case.


Relevant Papers:

M. W. Kadous, GRASP: Recognition of Australian Sign Language using Instrumented Gloves, Honours thesis, School of Computer Science and Engineering, University of New South Wales, 1995.
[Web Link]


Papers That Cite This Data Set1:


Mohammed Waleed Kadous and Claude Sammut. The University of New South Wales School of Computer Science and Engineering Temporal Classification: Extending the Classification Paradigm to Multivariate Time Series. [View Context].



Citation Request:

The data may be used provided that:
-The source of the data ([Web Link]) is acknowledged.
-If you publish any work using the dataset, please inform the donor.
-Use for commercial purposes requires donor permission.
"""